main: sdb.px.sdb. (string dupers back)
version: 1.0.0
name: sdb. (string dupers back)
author: pxotitas
description: bringing back string dupers for minecraft, on a configurable way. just it.
api-version: 1.21


